### ISSUE TITLE
DRBD 9.2.5 for Talos v1.5.3

### ISSUE THREAD

**Issue by Nosmoht** [siderolabs/extensions#238]
I would like to use DRBD 9.2.5 with Talos v1.5.3. Currently the DRBD 9.2.5 extension is only available for Talos v1.6.0-*. Would you please add the new DRBD version for Talos v1.5.3?

**Comment by smira** [comment]
We usually don't update extensions in the minor releases, is there any big reason for the bump?

**Comment by Nosmoht** [comment]
I just want to use the new [Piraeus Operator v2.2](https://github.com/piraeusdatastore/piraeus-operator/releases/tag/v2.2.0) as i have some trouble with the older version. And the new versions is looking for DRBD 9.2.5 module.

**Comment by smira** [comment]
That's always the case with software, the released version doesn't often update packages. If there's a security issue, or a data loss bug, we're happy to update.

**Comment by Ulrar** [comment]
Hi,

Any chance we could get an update for 1.5.5 ? I believe the latest version is 9.2.6.
I'm having a lot of issues with it (see https://github.com/piraeusdatastore/piraeus-operator/issues/579), although it's hard to say if it's caused by the DRBD version or not.

Maybe I could try building an updated extension image myself, I'm not sure what's involved but I see instructions to build in the readme, would talos accept being pointed at a non official extension image ?
Thanks

**Comment by smira** [comment]
You can build your own image with any system extension, but as drbd is a kernel module, this will require a full kernel rebuild.

Talos 1.6.0 is going to be released today
